# This section declares settings for the server.
[server]
host = "0.0.0.0"        # server host
port = 8050             # server port

# This section declares setting for the database.
[database]
file = "data/gorse.db"  # database file

# This section declares settings for recommendation.
[recommend]
model = "knn_implicit"  # recommendation model
cache_size = 100        # the number of cached recommendations
update_threshold = 1   # update model when more than 1 ratings are added
check_period = 5        # check for update every 10 second
similarity = "implicit" # similarity metric for neighbors

# This section declares hyperparameters for the recommendation model.
[params]
